# Generated by Django 2.2 on 2022-09-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='news_count',
        ),
    ]
