# Generated by Django 2.2 on 2022-08-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0002_auto_20220803_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=2, max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
