# Generated by Django 2.2 on 2022-08-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0004_auto_20220803_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='count_view',
        ),
    ]
