# Generated by Django 2.2 on 2022-08-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0012_auto_20220822_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-create_date'], 'permissions': (('create', 'Может публиковать'), ('edit', 'Может редактировать')), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
