# Generated by Django 2.2 on 2022-08-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0015_auto_20220825_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='teg',
        ),
        migrations.AddField(
            model_name='tegs',
            name='news',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_news.News'),
        ),
    ]
