# Generated by Django 2.2 on 2022-08-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0018_auto_20220829_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(default=None, null=True, on_delete=None, to='app_news.Tegs'),
        ),
    ]
