# Generated by Django 2.2 on 2022-09-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0019_auto_20220829_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['create_date'], 'permissions': (('create', 'Может публиковать'), ('edit', 'Может редактировать')), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='blog_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/'),
        ),
    ]
