# Generated by Django 2.2 on 2022-09-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0021_auto_20220908_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=None, to='app_news.Tegs'),
        ),
    ]
