# Generated by Django 2.2 on 2022-08-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('comment_text', models.CharField(max_length=1000, verbose_name='Текст комментария')),
                ('create_comment_date', models.DateTimeField(auto_now_add=True)),
                ('news_id', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-create_comment_date'],
            },
        ),
    ]
