# Generated by Django 2.2 on 2022-08-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='Comments',
        ),
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
    ]
